version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    networks:
      - pawn_application_network

  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - pawn_application_network
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - pawn_application_network

networks:
  pawn_application_network:
    driver: bridge
